#!/bin/bash
clear
git clone https://github.com/bolontiku/scriptcopy
cd scriptcopy/

chmod +777 Scriptcopy
chmod +777 scriptcopy-up

clear
for i in $(seq 1 100)
do
    sleep 0.03 
    echo $i
done | dialog --title '| Hecho por Código Cristo |' --gauge "\nVisite la comunidad >> t.me/ArchLinuxCristo <<\n " 8 53 0


cp .dialogrc ~/.dialogrc
cp Scriptcopy /bin/scriptcopy
cp arcris-up /bin/scriptcopy-up

cd ..
rm -r scriptcopy
clear
scriptcopy
